"""Quantitative tables (thesis Tables: tab:nerf_osr and tab:synthetic).

- nerf_osr: outdoor relighting on the NeRF-OSR benchmark (PSNR / MSE per
  site). Baseline rows (NeRF-OSR, FEGR, SOL-NeRF) are the published numbers;
  the NeuSky row is computed by evaluating each site's checkpoint with the
  benchmark protocol (eval_latent_optimise_method="nerf_osr_holdout" with the
  per-session holdout indices, masked metrics via the provided test masks).
- synthetic: novel view + intrinsic decomposition on the five synthetic
  scenes (PSNR / SSIM / LPIPS / Albedo PSNR / Normal MAE; roughness and
  metallic are not predicted by NeuSky and emit ---).

Both emit .tex and .csv next to a JSON metrics cache; pass --scenes to run a
partial set (e.g. only lk2 while st/lwp refits are pending) — missing scenes
render as --- and can be filled in by re-running once their runs exist.

Checkpoint-dependent (GPU):

    PYTHONPATH=. python scripts/figures/make_tables.py
    PYTHONPATH=. python scripts/figures/make_tables.py --tables nerf_osr --scenes lk2
"""

import argparse
import csv
import json
from pathlib import Path

from _common import (SCENE_TO_SITE, SESSION_HOLDOUT_INDICES, SYNTHETIC_SCENES,
                     TABLES_DIR, canonical_scene, load_model, resolve_run_dir)

NERF_OSR_SCENES = ("lk2", "st", "lwp")  # site1, site2, site3

# Published baselines for tab:nerf_osr (PSNR up, MSE down), per site.
NERF_OSR_BASELINES = {
    "NeRF-OSR~\\cite{rudnev_nerf_2022}": {
        "lk2": (19.34, 0.012), "st": (16.35, 0.027), "lwp": (15.66, 0.029)},
    "FEGR~\\cite{wang_neural_2023}": {
        "lk2": (21.53, 0.007), "st": (17.00, 0.023), "lwp": (17.57, 0.018)},
    "SOL-NeRF~\\cite{sunSOLNeRFSunlightModeling2023}": {
        "lk2": (21.23, 0.0084), "st": (18.18, 0.019), "lwp": (17.58, 0.028)},
}

SYNTHETIC_METRICS = ("psnr", "ssim", "lpips", "albedo_psnr", "normal_mae")


def has_run(scene: str) -> bool:
    try:
        resolve_run_dir(scene)
        return True
    except FileNotFoundError:
        return False


def evaluate_nerfosr_relighting(scene: str, device: str):
    """NeuSky relighting metrics for one NeRF-OSR site (psnr, mse)."""
    import torch

    def hook(config):
        config.pipeline.model.eval_latent_optimise_method = "nerf_osr_holdout"
        config.pipeline.datamanager.dataparser.session_holdout_indices = \
            SESSION_HOLDOUT_INDICES[scene]

    _, pipeline, _, step = load_model(scene, device=device, config_hook=hook)
    metrics = pipeline.get_average_eval_image_metrics(step=step)
    result = {"psnr": float(metrics["psnr"]), "mse": float(metrics["mse"])}
    del pipeline
    torch.cuda.empty_cache()
    return result


def evaluate_synthetic(scene: str, device: str):
    """NeuSky synthetic-benchmark metrics for one scene."""
    import torch

    _, pipeline, _, step = load_model(scene, device=device)
    metrics = pipeline.get_average_eval_image_metrics(step=step)
    result = {m: float(metrics[m]) for m in SYNTHETIC_METRICS if m in metrics}
    del pipeline
    torch.cuda.empty_cache()
    return result


def collect(scenes, evaluator, cache_path: Path, device: str, prefix: str):
    results = {}
    if cache_path.exists():
        results = json.loads(cache_path.read_text())
        print(f"[cache] loaded {len(results)} entries from {cache_path}")
    for scene in scenes:
        key = f"{prefix}/{scene}"
        if key in results:
            continue
        if not has_run(scene):
            print(f"[skip] {key}: no run with checkpoints (cells will show ---)")
            results[key] = None
        else:
            print(f"[eval] {key}")
            results[key] = evaluator(scene, device)
        cache_path.parent.mkdir(parents=True, exist_ok=True)
        cache_path.write_text(json.dumps(results, indent=2))
    return results


def fmt(value, best, decimals, lower_better=False):
    s = f"{value:.{decimals}f}"
    is_best = (value <= best) if lower_better else (value >= best)
    return f"\\textbf{{{s}}}" if is_best else s


def write_nerf_osr_table(results, output: Path):
    rows = dict(NERF_OSR_BASELINES)
    neusky = {s: results.get(f"nerf_osr/{s}") for s in NERF_OSR_SCENES}
    rows["NeuSky (Ours)"] = {
        s: (r["psnr"], r["mse"]) if r else None for s, r in neusky.items()}
    # Baselines store tuples directly; normalise.
    for name in NERF_OSR_BASELINES:
        rows[name] = {s: tuple(v) for s, v in NERF_OSR_BASELINES[name].items()}

    best = {}
    for s in NERF_OSR_SCENES:
        vals = [v[s] for v in rows.values() if v.get(s) is not None]
        best[s] = (max(v[0] for v in vals), min(v[1] for v in vals))

    lines = [
        "% Generated by scripts/figures/make_tables.py -- do not edit by hand",
        "\\begin{tabular}{@{}lcccccccc@{}}",
        "\\toprule",
        "& \\multicolumn{2}{c}{Site 1} & \\phantom{ab} & \\multicolumn{2}{c}{Site 2}"
        " & \\phantom{ab} & \\multicolumn{2}{c}{Site 3} \\\\",
        "& PSNR $\\uparrow$ & MSE $\\downarrow$ && PSNR $\\uparrow$ & MSE $\\downarrow$"
        " && PSNR $\\uparrow$ & MSE $\\downarrow$ \\\\",
        "\\midrule",
    ]
    csv_rows = [("method",) + tuple(
        f"{SCENE_TO_SITE[s]}_{m}" for s in NERF_OSR_SCENES for m in ("psnr", "mse"))]
    for name, per_scene in rows.items():
        cells, csv_cells = [], []
        for s in NERF_OSR_SCENES:
            v = per_scene.get(s)
            if v is None:
                cells.append("--- & ---")
                csv_cells.extend(["", ""])
            else:
                psnr, mse = v
                cells.append(f"{fmt(psnr, best[s][0], 2)} & "
                             f"{fmt(mse, best[s][1], 3, lower_better=True)}")
                csv_cells.extend([f"{psnr:.4f}", f"{mse:.4f}"])
        lines.append(f"{name} & " + " && ".join(cells) + " \\\\")
        csv_rows.append((name, *csv_cells))
    lines += ["\\bottomrule", "\\end{tabular}"]

    output.parent.mkdir(parents=True, exist_ok=True)
    output.with_suffix(".tex").write_text("\n".join(lines) + "\n")
    with open(output.with_suffix(".csv"), "w", newline="") as f:
        csv.writer(f).writerows(csv_rows)
    print(f"[saved] {output}.tex / .csv")
    print("\n".join(lines))


def write_synthetic_table(results, output: Path):
    decimals = {"psnr": 2, "ssim": 3, "lpips": 3, "albedo_psnr": 2, "normal_mae": 2}
    lines = [
        "% Generated by scripts/figures/make_tables.py -- do not edit by hand",
        "\\begin{tabular}{@{}lcccccccc@{}}",
        "\\toprule",
        " & \\multicolumn{3}{c}{Novel View} & \\multicolumn{4}{c}{Intrinsic Decomposition} \\\\",
        "\\cmidrule(lr){2-4} \\cmidrule(lr){5-8}",
        "Scene & PSNR $\\uparrow$ & SSIM $\\uparrow$ & LPIPS $\\downarrow$ & "
        "Albedo PSNR $\\uparrow$ & Normal MAE $\\downarrow$ & "
        "Rough. PSNR $\\uparrow$ & Metal. PSNR $\\uparrow$ \\\\",
        "\\midrule",
    ]
    csv_rows = [("scene", *SYNTHETIC_METRICS)]
    collected = {m: [] for m in SYNTHETIC_METRICS}
    for scene, label in SYNTHETIC_SCENES.items():
        r = results.get(f"synthetic/{scene}")
        if r is None:
            lines.append(f"{label} & " + " & ".join(["---"] * 7) + " \\\\")
            csv_rows.append((scene, "", "", "", "", ""))
            continue
        cells = [f"{r[m]:.{decimals[m]}f}" if m in r else "---"
                 for m in SYNTHETIC_METRICS]
        for m in SYNTHETIC_METRICS:
            if m in r:
                collected[m].append(r[m])
        lines.append(f"{label} & " + " & ".join(cells) + " & --- & --- \\\\")
        csv_rows.append((scene, *(f"{r.get(m, float('nan')):.4f}" for m in SYNTHETIC_METRICS)))

    lines.append("\\midrule")
    if any(collected[m] for m in SYNTHETIC_METRICS):
        mean_cells = [
            f"\\textbf{{{sum(v) / len(v):.{decimals[m]}f}}}" if (v := collected[m]) else "---"
            for m in SYNTHETIC_METRICS
        ]
        lines.append("\\textbf{Mean} & " + " & ".join(mean_cells) + " & --- & --- \\\\")
        csv_rows.append(("mean", *(
            f"{sum(v) / len(v):.4f}" if (v := collected[m]) else "" for m in SYNTHETIC_METRICS)))
    lines += ["\\bottomrule", "\\end{tabular}"]

    output.parent.mkdir(parents=True, exist_ok=True)
    output.with_suffix(".tex").write_text("\n".join(lines) + "\n")
    with open(output.with_suffix(".csv"), "w", newline="") as f:
        csv.writer(f).writerows(csv_rows)
    print(f"[saved] {output}.tex / .csv")
    print("\n".join(lines))


def main():
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--device", default="cuda:0")
    parser.add_argument("--tables", nargs="+", choices=["nerf_osr", "synthetic"],
                        default=["nerf_osr", "synthetic"])
    parser.add_argument("--scenes", nargs="*", default=None,
                        help="Restrict evaluation to these scenes (others show ---). "
                             "E.g. --scenes lk2 for a partial lk2-only run.")
    parser.add_argument("--output-dir", type=Path, default=TABLES_DIR)
    parser.add_argument("--cache", type=Path, default=None,
                        help="JSON metrics cache (default <output-dir>/neusky_metrics.json)")
    args = parser.parse_args()

    wanted = {canonical_scene(s) for s in args.scenes} if args.scenes else None
    cache_path = args.cache or args.output_dir / "neusky_metrics.json"

    if "nerf_osr" in args.tables:
        scenes = [s for s in NERF_OSR_SCENES if wanted is None or s in wanted]
        results = collect(scenes, evaluate_nerfosr_relighting, cache_path,
                          args.device, "nerf_osr")
        write_nerf_osr_table(results, args.output_dir / "nerf_osr")

    if "synthetic" in args.tables:
        scenes = [s for s in SYNTHETIC_SCENES if wanted is None or s in wanted]
        results = collect(scenes, evaluate_synthetic, cache_path,
                          args.device, "synthetic")
        write_synthetic_table(results, args.output_dir / "synthetic")


if __name__ == "__main__":
    main()
